x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./scripts:/opt/project-scripts:ro
    - ./tests:/opt/airflow/tests
    - ./secrets:/opt/airflow/secrets:ro
    - ./data:/opt/airflow/data
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:16
    env_file: .env
    entrypoint: ["/bin/bash", "/opt/project-scripts/postgres-with-db-password.sh"]
    command: ["postgres"]
    ports:
      - "5444:5432"
    volumes:
      - ./scripts:/opt/project-scripts:ro
      - ./secrets:/opt/airflow/secrets:ro
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-airflow}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  airflow-init:
    <<: *airflow-common
    env_file: .env
    entrypoint: ["/bin/bash", "/opt/project-scripts/airflow-with-db-password.sh"]
    command: ["/bin/bash", "-lc", "airflow db migrate && airflow users create --username ${AIRFLOW_ADMIN_USER:-airflow} --password ${AIRFLOW_ADMIN_PASSWORD:-airflow} --firstname Air --lastname Flow --role Admin --email ${AIRFLOW_ADMIN_EMAIL:-admin@example.com}"]

  airflow-webserver:
    <<: *airflow-common
    env_file: .env
    entrypoint: ["/bin/bash", "/opt/project-scripts/airflow-with-db-password.sh"]
    command: ["airflow", "webserver"]
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1

  airflow-scheduler:
    <<: *airflow-common
    env_file: .env
    entrypoint: ["/bin/bash", "/opt/project-scripts/airflow-with-db-password.sh"]
    command: ["airflow", "scheduler"]
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  postgres-db-volume:
